@extends('layouts.app')

@section('title', 'Events Calendar')
@section('page-title', 'Events Calendar')

@section('content')
<div class="space-y-6">
    <!-- Header with Actions -->
    <div class="flex flex-col sm:flex-row sm:items-center sm:justify-between gap-4">
        <div>
            <h2 class="text-2xl font-bold text-gray-900">Events Calendar</h2>
            <p class="text-gray-600 text-sm mt-1">View all events in calendar format</p>
        </div>
        <div class="flex gap-2">
            @if(auth()->user()->hasRole(['Admin', 'Manager']))
                <a href="{{ route('events.create') }}" class="inline-flex items-center px-4 py-2 bg-blue-600 text-white rounded-xl hover:bg-blue-700 transition-colors font-medium">
                    <i class="fas fa-plus mr-2"></i>
                    Add Event
                </a>
            @endif
            <a href="{{ route('events.index') }}" class="inline-flex items-center px-4 py-2 bg-gray-200 text-gray-800 rounded-xl hover:bg-gray-300 transition-colors font-medium">
                <i class="fas fa-list mr-2"></i>
                Table View
            </a>
        </div>
    </div>

    <!-- Calendar Container -->
    <div class="bg-white rounded-3xl shadow-xl overflow-hidden">
        <!-- Calendar Header with Navigation -->
        <div class="bg-gradient-to-br from-blue-50 to-blue-100 px-8 py-8">
            <div class="flex items-center justify-between">
                <!-- Left Navigation -->
                <button onclick="previousMonth()" class="w-12 h-12 rounded-full bg-white shadow-md hover:shadow-lg text-gray-800 font-bold text-xl transition-all hover:scale-110">
                    <i class="fas fa-chevron-left"></i>
                </button>

                <!-- Month and Year -->
                <div class="text-center">
                    <h3 class="text-4xl font-bold text-gray-900" id="monthYear">January 2026</h3>
                </div>

                <!-- Right Navigation -->
                <button onclick="nextMonth()" class="w-12 h-12 rounded-full bg-white shadow-md hover:shadow-lg text-gray-800 font-bold text-xl transition-all hover:scale-110">
                    <i class="fas fa-chevron-right"></i>
                </button>
            </div>
        </div>

        <!-- Calendar Grid -->
        <div class="p-8">
            <!-- Calendar Table -->
            <div class="border-2 border-gray-300 rounded-xl overflow-hidden shadow-sm">
                <!-- Days of Week Header -->
                <div class="grid grid-cols-7 bg-gradient-to-r from-gray-50 to-gray-100 border-b-2 border-gray-300">
                    @foreach(['Mo', 'Tu', 'We', 'Th', 'Fr', 'Sa', 'Su'] as $day)
                        <div class="text-center font-bold text-gray-800 py-4 text-base border-r border-gray-300 last:border-r-0">{{ $day }}</div>
                    @endforeach
                </div>

                <!-- Calendar Days Grid -->
                <div id="calendarGrid" class="grid grid-cols-7">
                    <!-- Calendar days will be generated by JavaScript -->
                </div>
            </div>
        </div>
    </div>

    <!-- Events Details Section -->
    <div class="bg-white rounded-3xl shadow-xl overflow-hidden">
        <div class="bg-gradient-to-br from-blue-600 to-blue-700 px-8 py-6">
            <h3 class="text-xl font-bold text-white">
                <i class="fas fa-calendar-check mr-2"></i>
                Events for <span id="selectedDate">Today</span>
            </h3>
        </div>
        <div class="p-8">
            <div id="eventsList" class="space-y-4">
                <!-- Events will be listed here -->
            </div>
        </div>
    </div>
</div>

<style>
    .calendar-day {
        @apply relative min-h-36 cursor-pointer transition-all duration-300 ease-in-out bg-white border-r border-b last:border-r-0 hover:bg-gradient-to-br hover:from-blue-50 hover:to-indigo-50 hover:shadow-lg hover:scale-[1.02] hover:z-10;
        border: 1px solid #e2e2e2;
        box-shadow: 0 8px 32px rgba(0, 0, 0, 0.05);
        padding: 15px;
        backdrop-filter: blur(10px);
        background: linear-gradient(135deg, rgba(255, 255, 255, 0.95) 0%, rgba(248, 250, 252, 0.95) 100%);
    }
    
    .calendar-day:nth-child(7n) {
        @apply border-r-0;
    }
    
    .calendar-day::before {
        content: '';
        position: absolute;
        top: 0;
        left: 0;
        right: 0;
        bottom: 0;
        background: linear-gradient(135deg, rgba(59, 130, 246, 0.05) 0%, rgba(99, 102, 241, 0.05) 100%);
        opacity: 0;
        transition: opacity 0.3s ease;
        pointer-events: none;
    }
    
    .calendar-day:hover::before {
        opacity: 1;
    }
    
    .calendar-day.other-month {
        @apply bg-gray-50 text-gray-400;
        background: linear-gradient(135deg, rgba(249, 250, 251, 0.8) 0%, rgba(243, 244, 246, 0.8) 100%);
    }
    
    .calendar-day.today {
        @apply bg-gradient-to-br from-blue-100 via-blue-50 to-indigo-50 border-blue-300 shadow-lg ring-2 ring-blue-200 ring-opacity-50;
        background: linear-gradient(135deg, rgba(219, 234, 254, 0.9) 0%, rgba(238, 242, 255, 0.9) 100%);
        transform: translateY(-2px);
    }
    
    .calendar-day.today::after {
        content: '';
        position: absolute;
        top: 8px;
        right: 8px;
        width: 8px;
        height: 8px;
        background: linear-gradient(45deg, #3b82f6, #6366f1);
        border-radius: 50%;
        box-shadow: 0 0 0 2px rgba(59, 130, 246, 0.3);
        animation: pulse 2s infinite;
    }
    
    .calendar-day.selected {
        @apply bg-gradient-to-br from-blue-600 via-blue-700 to-indigo-700 text-white shadow-2xl ring-4 ring-blue-300 ring-opacity-50;
        transform: translateY(-4px);
    }
    
    .calendar-day.selected .day-number {
        @apply text-white font-bold;
    }
    
    .calendar-day.selected .event-badge {
        @apply bg-white bg-opacity-20 text-white border border-white border-opacity-30;
        backdrop-filter: blur(10px);
    }
    
    .calendar-day.has-events {
        @apply bg-gradient-to-br from-blue-25 via-white to-blue-25;
        background: linear-gradient(135deg, rgba(248, 250, 255, 0.95) 0%, rgba(255, 255, 255, 0.95) 50%, rgba(248, 250, 255, 0.95) 100%);
    }
    
    .calendar-day.has-events:not(.selected):not(.today) {
        @apply border-blue-200;
    }
    
    .calendar-day.has-events::after {
        content: '';
        position: absolute;
        top: 6px;
        left: 6px;
        width: 6px;
        height: 6px;
        background: linear-gradient(45deg, #10b981, #059669);
        border-radius: 50%;
        box-shadow: 0 0 0 2px rgba(16, 185, 129, 0.2);
    }
    
    .event-badge {
        @apply text-xs px-3 py-1.5 rounded-full font-semibold mb-2 block truncate whitespace-nowrap overflow-hidden shadow-sm border border-opacity-20;
        backdrop-filter: blur(5px);
        transition: all 0.2s ease;
    }
    
    .event-badge:hover {
        @apply transform scale-105 shadow-md;
    }
    
    .event-badge.pending {
        @apply bg-gradient-to-r from-amber-100 to-yellow-100 text-amber-800 border-amber-200;
    }
    
    .event-badge.completed {
        @apply bg-gradient-to-r from-emerald-100 to-green-100 text-emerald-800 border-emerald-200;
    }
    
    .event-badge.cancelled {
        @apply bg-gradient-to-r from-red-100 to-rose-100 text-red-800 border-red-200;
    }
    
    .day-number {
        @apply font-bold text-gray-900 mb-3 text-xl leading-none;
        text-shadow: 0 1px 2px rgba(0, 0, 0, 0.05);
    }
    
    .calendar-day.other-month .day-number {
        @apply text-gray-400 font-medium;
    }
    
    .calendar-day.today .day-number {
        @apply text-blue-800 font-extrabold text-2xl;
        text-shadow: 0 2px 4px rgba(59, 130, 246, 0.2);
    }
    
    .calendar-day.selected .day-number {
        @apply text-white font-extrabold text-2xl;
        text-shadow: 0 2px 4px rgba(0, 0, 0, 0.3);
    }
    
    .event-item {
        @apply border-l-4 border-blue-500 bg-gradient-to-r from-blue-50 via-white to-transparent p-6 rounded-2xl hover:shadow-xl transition-all duration-300 hover:transform hover:scale-[1.02];
        backdrop-filter: blur(10px);
        background: linear-gradient(135deg, rgba(239, 246, 255, 0.8) 0%, rgba(255, 255, 255, 0.9) 50%, rgba(255, 255, 255, 0.8) 100%);
    }
    
    .event-item.pending {
        @apply border-l-amber-500;
        background: linear-gradient(135deg, rgba(254, 243, 199, 0.8) 0%, rgba(255, 255, 255, 0.9) 50%, rgba(255, 255, 255, 0.8) 100%);
    }
    
    .event-item.completed {
        @apply border-l-emerald-500;
        background: linear-gradient(135deg, rgba(209, 250, 229, 0.8) 0%, rgba(255, 255, 255, 0.9) 50%, rgba(255, 255, 255, 0.8) 100%);
    }
    
    .event-item.cancelled {
        @apply border-l-red-500;
        background: linear-gradient(135deg, rgba(254, 226, 226, 0.8) 0%, rgba(255, 255, 255, 0.9) 50%, rgba(255, 255, 255, 0.8) 100%);
    }
    
    /* Custom blue-25 color for subtle highlighting */
    .bg-blue-25 {
        background-color: #f8faff;
    }
    
    .from-blue-25 {
        --tw-gradient-from: #f8faff;
        --tw-gradient-to: rgb(248 250 255 / 0);
        --tw-gradient-stops: var(--tw-gradient-from), var(--tw-gradient-to);
    }
    
    /* Pulse animation for today indicator */
    @keyframes pulse {
        0%, 100% {
            opacity: 1;
            transform: scale(1);
        }
        50% {
            opacity: 0.7;
            transform: scale(1.1);
        }
    }
    
    /* Smooth scrolling and enhanced interactions */
    .calendar-day {
        position: relative;
        overflow: hidden;
    }
    
    .calendar-day:hover .day-number {
        @apply transform scale-110;
        transition: transform 0.2s ease;
    }
    
    .calendar-day:hover .event-badge {
        @apply transform translate-x-1;
        transition: transform 0.2s ease;
    }
    
    /* Glass morphism effect for modern look */
    .calendar-day:hover {
        box-shadow: 0 16px 48px rgba(59, 130, 246, 0.15);
        border: 1px solid #d1d5db;
    }
    
    .calendar-day.today {
        box-shadow: 0 16px 48px rgba(59, 130, 246, 0.2);
        border: 1px solid #93c5fd;
    }
    
    .calendar-day.selected {
        box-shadow: 0 20px 60px rgba(59, 130, 246, 0.3);
        border: 1px solid #3b82f6;
    }
</style>

@push('scripts')
<script>
let currentDate = new Date();
const events = @json($events);

function renderCalendar() {
    const year = currentDate.getFullYear();
    const month = currentDate.getMonth();
    
    // Update month/year display
    const monthNames = ['January', 'February', 'March', 'April', 'May', 'June',
                       'July', 'August', 'September', 'October', 'November', 'December'];
    document.getElementById('monthYear').textContent = `${monthNames[month]} ${year}`;
    
    const firstDay = new Date(year, month, 1);
    const lastDay = new Date(year, month + 1, 0);
    const daysInMonth = lastDay.getDate();
    const startingDayOfWeek = firstDay.getDay();

    const calendarGrid = document.getElementById('calendarGrid');
    calendarGrid.innerHTML = '';

    // Previous month days
    const prevMonthLastDay = new Date(year, month, 0).getDate();
    for (let i = startingDayOfWeek - 1; i >= 0; i--) {
        const day = prevMonthLastDay - i;
        const dayElement = createDayElement(day, true);
        calendarGrid.appendChild(dayElement);
    }

    // Current month days
    for (let day = 1; day <= daysInMonth; day++) {
        const dayElement = createDayElement(day, false, year, month);
        calendarGrid.appendChild(dayElement);
    }

    // Next month days
    const remainingDays = 42 - (startingDayOfWeek + daysInMonth);
    for (let day = 1; day <= remainingDays; day++) {
        const dayElement = createDayElement(day, true);
        calendarGrid.appendChild(dayElement);
    }
}

function createDayElement(day, isOtherMonth, year, month) {
    const dayElement = document.createElement('div');
    dayElement.className = 'calendar-day';
    
    if (isOtherMonth) {
        dayElement.classList.add('other-month');
        dayElement.innerHTML = `<div class="day-number">${day}</div>`;
    } else {
        const date = new Date(year, month, day);
        const today = new Date();
        today.setHours(0, 0, 0, 0);
        
        if (date.getTime() === today.getTime()) {
            dayElement.classList.add('today');
        }
        
        if (date.getTime() === selectedDate.getTime()) {
            dayElement.classList.add('selected');
        }

        // Get events for this day
        const dayEvents = events.filter(e => {
            const eventDate = new Date(e.start_date);
            return eventDate.toDateString() === date.toDateString();
        });

        if (dayEvents.length > 0) {
            dayElement.classList.add('has-events');
        }

        let html = `<div class="day-number">${day}</div>`;
        
        // Add event badges
        dayEvents.slice(0, 2).forEach(event => {
            html += `<div class="event-badge ${event.status}">${event.event_name}</div>`;
        });

        if (dayEvents.length > 2) {
            html += `<div class="text-xs text-blue-600 font-semibold mt-1">+${dayEvents.length - 2} more</div>`;
        }

        dayElement.innerHTML = html;
        dayElement.addEventListener('click', () => selectDate(date));
    }

    return dayElement;
}

let selectedDate = new Date();
selectedDate.setHours(0, 0, 0, 0);

function selectDate(date) {
    selectedDate = new Date(date);
    selectedDate.setHours(0, 0, 0, 0);
    renderCalendar();
    updateEventsList();
}

function updateEventsList() {
    const eventsList = document.getElementById('eventsList');
    const selectedDateStr = selectedDate.toLocaleDateString('en-US', { 
        weekday: 'long', 
        year: 'numeric', 
        month: 'long', 
        day: 'numeric' 
    });
    document.getElementById('selectedDate').textContent = selectedDateStr;

    const dayEvents = events.filter(e => {
        const eventDate = new Date(e.start_date);
        return eventDate.toDateString() === selectedDate.toDateString();
    });

    if (dayEvents.length === 0) {
        eventsList.innerHTML = `
            <div class="text-center py-12">
                <i class="fas fa-calendar-times text-4xl text-gray-300 mb-3"></i>
                <p class="text-gray-500 text-lg">No events scheduled for this date</p>
            </div>
        `;
    } else {
        eventsList.innerHTML = dayEvents.map(event => `
            <div class="event-item ${event.status}">
                <div class="flex items-start justify-between">
                    <div class="flex-1">
                        <div class="flex items-center gap-2 mb-2">
                            <h4 class="font-bold text-gray-900 text-lg">${event.event_name}</h4>
                            <span class="inline-block px-2 py-1 rounded-full text-xs font-semibold
                                ${event.status === 'completed' ? 'bg-green-100 text-green-800' : 
                                  event.status === 'pending' ? 'bg-yellow-100 text-yellow-800' : 
                                  'bg-red-100 text-red-800'}">
                                ${event.status.charAt(0).toUpperCase() + event.status.slice(1)}
                            </span>
                        </div>
                        <p class="text-sm text-gray-600 mb-2">
                            <i class="fas fa-map-marker-alt text-purple-600 mr-2"></i>
                            <strong>Location:</strong> ${event.location}
                        </p>
                        <p class="text-sm text-gray-600 mb-2">
                            <i class="fas fa-clock text-purple-600 mr-2"></i>
                            <strong>Time:</strong> ${new Date(event.start_date).toLocaleTimeString('en-US', { hour: '2-digit', minute: '2-digit' })} - ${new Date(event.end_date).toLocaleTimeString('en-US', { hour: '2-digit', minute: '2-digit' })}
                        </p>
                        <p class="text-sm text-gray-700 mt-3 p-3 bg-white rounded border-l-2 border-purple-400">
                            <strong>Description:</strong> ${event.description}
                        </p>
                    </div>
                    <a href="/events/${event.id}" class="ml-4 px-4 py-2 bg-purple-600 text-white rounded-lg hover:bg-purple-700 transition-colors text-sm font-medium whitespace-nowrap">
                        <i class="fas fa-arrow-right mr-1"></i>View
                    </a>
                </div>
            </div>
        `).join('');
    }
}

function previousMonth() {
    currentDate.setMonth(currentDate.getMonth() - 1);
    renderCalendar();
}

function nextMonth() {
    currentDate.setMonth(currentDate.getMonth() + 1);
    renderCalendar();
}

function goToToday() {
    currentDate = new Date();
    selectDate(new Date());
}

// Initialize
renderCalendar();
updateEventsList();
</script>
@endpush
@endsection
